# import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv('insurance.csv')

In [29]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [31]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(1)

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
df.sex = df.sex.replace({
    'male':1,
    'female':0
})

C:\Users\PMLS\AppData\Local\Temp\ipykernel_9104\2333064529.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.sex = df.sex.replace({

In [35]:
df.smoker=df.smoker.replace({
    'yes':1,
    'no':0
})

C:\Users\PMLS\AppData\Local\Temp\ipykernel_9104\503969230.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.smoker=df.smoker.replace({

In [36]:
df = pd.get_dummies(df, dtype=int)

In [37]:
df.head()

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               1337 non-null   int64
 1   sex               1337 non-null   int64
 2   bmi               1337 non-null   float64
 3   children          1337 non-null   int64
 4   smoker            1337 non-null   int64
 5   charges           1337 non-null   float64
 6   region_northeast  1337 non-null   int64
 7   region_northwest  1337 non-null   int64
 8   region_southeast  1337 non-null   int64
 9   region_southwest  1337 non-null   int64
dtypes: float64(2), int64(8)
memory usage: 114.9 KB

In [39]:
X=df.drop('charges',axis=1)
y=df.charges

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [41]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [42]:
model.fit(X_train,y_train)

LinearRegression()

In [43]:
y_pred_test=model.predict(X_test)

In [44]:
from sklearn.metrics import mean_squared_error,r2_score

In [45]:
import math
math.sqrt(mean_squared_error(y_pred_test,y_test))

5956.342894363585

In [46]:
r2_score(y_pred_test,y_test)

0.6899520700504285

In [48]:
model

LinearRegression()

In [49]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges',
       'region_northeast', 'region_northwest', 'region_southeast',
       'region_southwest'],
      dtype='object')

In [50]:
def charges(age, sex, bmi, children, smoker,
       region_northeast, region_northwest, region_southeast,
       region_southwest):
    return model.predict([[age, sex, bmi, children, smoker,
       region_northeast, region_northwest, region_southeast,
       region_southwest]])

In [52]:
age=int(input("enter your age"))
sex=int(input('enter your sex'))
bmi=float(input('enter BMI'))
children=int(input('enter the number of childer'))
smoker=int(input('are you smoker yes== 1 no==0'))
region = input("Enter region (northeast/northwest/southeast/southwest): ").lower()

region_northeast = 1 if region == "northeast" else 0
region_northwest = 1 if region == "northwest" else 0
region_southeast = 1 if region == "southeast" else 0
region_southwest = 1 if region == "southwest" else 0

print("northeast:", region_northeast)
print("northwest:", region_northwest)
print("southeast:", region_southeast)
print("southwest:", region_southwest)

print(f'''your charges is \n  {charges(age, sex, bmi, children, smoker,
       region_northeast, region_northwest, region_southeast,
       region_southwest)}''')

enter your age 12
enter your sex 1
enter BMI 32
enter the number of childer 2
are you smoker yes== 1 no==0 1
Enter region (northeast/northwest/southeast/southwest):  northeast

northeast: 1
northwest: 0
southeast: 0
southwest: 0
your charges is
  [26126.5649737]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(